PRODUCTS = [
    # --- Electronics (1-10) ---
    {"id": 1, "name": "Budget Earbuds", "price": 999, "rating": 4.3, "category": "Electronics", "tags": ["audio", "earbuds", "budget"]},
    {"id": 2, "name": "Power Bank 10000mAh", "price": 699, "rating": 4.4, "category": "Electronics", "tags": ["power", "battery", "portable"]},
    {"id": 3, "name": "Wireless Headphones", "price": 2500, "rating": 4.6, "category": "Electronics", "tags": ["audio", "headphones", "noise-cancelling"]},
    {"id": 4, "name": "Bluetooth Speaker Mini", "price": 1299, "rating": 4.5, "category": "Electronics", "tags": ["audio", "speaker", "portable"]},
    {"id": 5, "name": "Gaming Mouse RGB", "price": 1800, "rating": 4.7, "category": "Electronics", "tags": ["gaming", "pc", "peripheral"]},
    {"id": 6, "name": "Mechanical Keyboard", "price": 3999, "rating": 4.8, "category": "Electronics", "tags": ["gaming", "pc", "typing"]},
    {"id": 7, "name": "USB-C Hub 5-in-1", "price": 1500, "rating": 4.2, "category": "Electronics", "tags": ["adapter", "laptop", "accessory"]},
    {"id": 8, "name": "HD Webcam", "price": 1750, "rating": 4.1, "category": "Electronics", "tags": ["video", "streaming", "work"]},
    {"id": 9, "name": "Smart Plug 2-Pack", "price": 1399, "rating": 4.0, "category": "Electronics", "tags": ["smart-home", "iot", "automation"]},
    {"id": 10, "name": "Premium In-Ear Monitors", "price": 4500, "rating": 4.9, "category": "Electronics", "tags": ["audio", "professional", "high-end"]},

    # --- Accessories & Wearables (11-20) ---
    {"id": 11, "name": "Phone Case Clear", "price": 199, "rating": 4.0, "category": "Accessories", "tags": ["case", "phone", "clear"]},
    {"id": 12, "name": "Smart Watch Pro", "price": 3500, "rating": 4.1, "category": "Wearables", "tags": ["watch", "smart", "health"]},
    {"id": 13, "name": "Laptop Sleeve 13-inch", "price": 799, "rating": 4.2, "category": "Accessories", "tags": ["laptop", "sleeve", "protection"]},
    {"id": 14, "name": "Fitness Band", "price": 1499, "rating": 4.0, "category": "Wearables", "tags": ["fitness", "band", "tracker"]},
    {"id": 15, "name": "Magnetic Phone Holder (Car)", "price": 450, "rating": 4.3, "category": "Accessories", "tags": ["car", "mount", "utility"]},
    {"id": 16, "name": "Leather Wallet", "price": 1100, "rating": 4.5, "category": "Accessories", "tags": ["leather", "men", "fashion"]},
    {"id": 17, "name": "Blue Light Glasses", "price": 850, "rating": 4.6, "category": "Wearables", "tags": ["eyewear", "work", "computer"]},
    {"id": 18, "name": "Watch Strap Silicone", "price": 350, "rating": 4.4, "category": "Accessories", "tags": ["watch", "strap", "sport"]},
    {"id": 19, "name": "Selfie Stick with Tripod", "price": 600, "rating": 3.9, "category": "Accessories", "tags": ["photo", "travel", "utility"]},
    {"id": 20, "name": "Premium UV Sunglasses", "price": 2800, "rating": 4.7, "category": "Wearables", "tags": ["fashion", "summer", "eyewear"]},

    # --- Footwear & Apparel (21-30) ---
    {"id": 21, "name": "Sport Running Shoes", "price": 1200, "rating": 4.2, "category": "Footwear", "tags": ["shoes", "sport", "running"]},
    {"id": 22, "name": "Casual Sneakers White", "price": 1599, "rating": 4.5, "category": "Footwear", "tags": ["shoes", "fashion", "casual"]},
    {"id": 23, "name": "Winter Hiking Boots", "price": 4200, "rating": 4.8, "category": "Footwear", "tags": ["shoes", "outdoor", "winter"]},
    {"id": 24, "name": "Unisex Cotton T-shirt", "price": 500, "rating": 4.1, "category": "Apparel", "tags": ["clothing", "basic", "cotton"]},
    {"id": 25, "name": "Denim Jeans Slim Fit", "price": 1800, "rating": 4.3, "category": "Apparel", "tags": ["clothing", "denim", "pants"]},
    {"id": 26, "name": "Hoodie Fleece", "price": 1350, "rating": 4.4, "category": "Apparel", "tags": ["clothing", "winter", "comfort"]},
    {"id": 27, "name": "Formal Leather Belt", "price": 950, "rating": 4.0, "category": "Accessories", "tags": ["belt", "leather", "formal"]},
    {"id": 28, "name": "Performance Socks 3-Pack", "price": 300, "rating": 4.6, "category": "Apparel", "tags": ["socks", "sport", "utility"]},
    {"id": 29, "name": "Summer Sandals", "price": 750, "rating": 3.8, "category": "Footwear", "tags": ["shoes", "summer", "casual"]},
    {"id": 30, "name": "Waterproof Rain Jacket", "price": 2900, "rating": 4.7, "category": "Apparel", "tags": ["clothing", "outdoor", "rain"]},

    # --- Bags & Luggage (31-40) ---
    {"id": 31, "name": "Backpack Classic", "price": 900, "rating": 4.0, "category": "Bags", "tags": ["bag", "travel", "school"]},
    {"id": 32, "name": "Laptop Backpack Premium", "price": 2100, "rating": 4.6, "category": "Bags", "tags": ["bag", "laptop", "business"]},
    {"id": 33, "name": "Crossbody Sling Bag", "price": 1150, "rating": 4.2, "category": "Bags", "tags": ["bag", "urban", "small"]},
    {"id": 34, "name": "Travel Duffel Bag 40L", "price": 2800, "rating": 4.5, "category": "Bags", "tags": ["luggage", "travel", "gym"]},
    {"id": 35, "name": "Small Camera Bag", "price": 1600, "rating": 4.4, "category": "Bags", "tags": ["camera", "photo", "gear"]},
    {"id": 36, "name": "Hard-Shell Carry-on Suitcase", "price": 4999, "rating": 4.7, "category": "Bags", "tags": ["luggage", "travel", "premium"]},
    {"id": 37, "name": "Tote Bag Canvas", "price": 400, "rating": 3.9, "category": "Bags", "tags": ["bag", "casual", "shopping"]},
    {"id": 38, "name": "Waist Pouch/Fanny Pack", "price": 700, "rating": 4.1, "category": "Bags", "tags": ["bag", "sport", "running"]},
    {"id": 39, "name": "Document Organizer Folder", "price": 550, "rating": 4.3, "category": "Accessories", "tags": ["work", "office", "utility"]},
    {"id": 40, "name": "Hydration Backpack", "price": 1900, "rating": 4.6, "category": "Bags", "tags": ["bag", "cycling", "outdoor"]},

    # --- Home & Lifestyle (41-50) ---
    {"id": 41, "name": "Stainless Steel Water Bottle", "price": 650, "rating": 4.5, "category": "Lifestyle", "tags": ["bottle", "hydration", "sport"]},
    {"id": 42, "name": "Smart Scale Digital", "price": 1700, "rating": 4.0, "category": "Lifestyle", "tags": ["health", "smart", "fitness"]},
    {"id": 43, "name": "Aromatherapy Diffuser", "price": 1050, "rating": 4.2, "category": "Home", "tags": ["home", "relax", "fragrance"]},
    {"id": 44, "name": "Electric Hand Blender", "price": 2200, "rating": 4.6, "category": "Home", "tags": ["kitchen", "appliance", "cooking"]},
    {"id": 45, "name": "Desk Lamp LED", "price": 1400, "rating": 4.4, "category": "Home", "tags": ["lighting", "work", "office"]},
    {"id": 46, "name": "Coffee Mug Set (2)", "price": 499, "rating": 4.3, "category": "Lifestyle", "tags": ["kitchen", "drink", "home"]},
    {"id": 47, "name": "Yoga Mat Non-Slip", "price": 1199, "rating": 4.7, "category": "Lifestyle", "tags": ["fitness", "yoga", "exercise"]},
    {"id": 48, "name": "Portable Camping Chair", "price": 899, "rating": 3.9, "category": "Outdoor", "tags": ["camping", "outdoor", "utility"]},
    {"id": 49, "name": "Memory Foam Pillow", "price": 1650, "rating": 4.5, "category": "Home", "tags": ["bedding", "sleep", "comfort"]},
    {"id": 50, "name": "Basic Tool Kit (15 pcs)", "price": 1999, "rating": 4.1, "category": "Home", "tags": ["utility", "tools", "diy"]},

    # --- Kitchen & Appliances (51–70) ---
     {"id": 51, "name": "Electric Kettle 1.5L", "price": 1200, "rating": 4.4, "category": "Home", "tags": ["kitchen", "appliance", "tea"]},
    {"id": 52, "name": "Toaster 2-Slice", "price": 1450, "rating": 4.2, "category": "Home", "tags": ["breakfast", "kitchen", "bread"]},
    {"id": 53, "name": "Rice Cooker 1.8L", "price": 2100, "rating": 4.5, "category": "Home", "tags": ["kitchen", "appliance", "cooking"]},
    {"id": 54, "name": "Air Fryer Compact", "price": 3600, "rating": 4.6, "category": "Home", "tags": ["cooking", "healthy", "kitchen"]},
    {"id": 55, "name": "Electric Iron", "price": 950, "rating": 4.1, "category": "Home", "tags": ["clothing", "laundry", "utility"]},
    {"id": 56, "name": "Vacuum Cleaner Portable", "price": 3200, "rating": 4.3, "category": "Home", "tags": ["cleaning", "home", "utility"]},
    {"id": 57, "name": "Induction Cooktop", "price": 2800, "rating": 4.4, "category": "Home", "tags": ["kitchen", "cooking", "electric"]},
    {"id": 58, "name": "Mixer Grinder 3 Jar", "price": 2500, "rating": 4.2, "category": "Home", "tags": ["cooking", "kitchen", "grinder"]},
    {"id": 59, "name": "Juicer Machine", "price": 3100, "rating": 4.5, "category": "Home", "tags": ["health", "juice", "kitchen"]},
    {"id": 60, "name": "Microwave Oven 20L", "price": 4800, "rating": 4.6, "category": "Home", "tags": ["appliance", "kitchen", "cooking"]},
    {"id": 61, "name": "Table Fan 3-Speed", "price": 1600, "rating": 4.1, "category": "Home", "tags": ["cooling", "summer", "home"]},
    {"id": 62, "name": "Ceiling Light Modern", "price": 2200, "rating": 4.4, "category": "Home", "tags": ["lighting", "decor", "modern"]},
    {"id": 63, "name": "Wall Clock Wooden", "price": 899, "rating": 4.3, "category": "Home", "tags": ["decor", "clock", "classic"]},
    {"id": 64, "name": "Room Air Purifier", "price": 4800, "rating": 4.5, "category": "Home", "tags": ["air", "health", "home"]},
    {"id": 65, "name": "Curtain Set (2 Panels)", "price": 999, "rating": 4.2, "category": "Home", "tags": ["decor", "curtain", "home"]},
    {"id": 66, "name": "LED Fairy Lights 10m", "price": 450, "rating": 4.6, "category": "Lifestyle", "tags": ["decor", "lighting", "party"]},
    {"id": 67, "name": "Scented Candle Jar", "price": 350, "rating": 4.4, "category": "Lifestyle", "tags": ["home", "relax", "fragrance"]},
    {"id": 68, "name": "Photo Frame Set (3)", "price": 699, "rating": 4.3, "category": "Home", "tags": ["decor", "photo", "frame"]},
    {"id": 69, "name": "Digital Alarm Clock", "price": 799, "rating": 4.0, "category": "Lifestyle", "tags": ["clock", "bedroom", "utility"]},
    {"id": 70, "name": "Storage Box Set", "price": 950, "rating": 4.5, "category": "Home", "tags": ["organization", "home", "utility"]},
]

# --- Stationery & Office (71–90) ---
PRODUCTS += [
    {"id": 71, "name": "Notebook A5 Ruled", "price": 120, "rating": 4.2, "category": "Stationery", "tags": ["notebook", "writing", "office"]},
    {"id": 72, "name": "Ball Pen Pack (10)", "price": 150, "rating": 4.0, "category": "Stationery", "tags": ["pen", "writing", "office"]},
    {"id": 73, "name": "Highlighter Set (5 Colors)", "price": 200, "rating": 4.5, "category": "Stationery", "tags": ["study", "marker", "notes"]},
    {"id": 74, "name": "Desk Organizer", "price": 850, "rating": 4.4, "category": "Office", "tags": ["desk", "organization", "work"]},
    {"id": 75, "name": "Wireless Mouse", "price": 599, "rating": 4.3, "category": "Electronics", "tags": ["pc", "peripheral", "wireless"]},
    {"id": 76, "name": "Keyboard + Mouse Combo", "price": 1199, "rating": 4.4, "category": "Electronics", "tags": ["pc", "combo", "office"]},
    {"id": 77, "name": "Laptop Stand Adjustable", "price": 950, "rating": 4.6, "category": "Accessories", "tags": ["work", "laptop", "ergonomic"]},
    {"id": 78, "name": "Sticky Notes Pack", "price": 120, "rating": 4.1, "category": "Stationery", "tags": ["notes", "study", "office"]},
    {"id": 79, "name": "Mini Whiteboard", "price": 499, "rating": 4.3, "category": "Office", "tags": ["planning", "work", "study"]},
    {"id": 80, "name": "Printer Paper A4 (500 Sheets)", "price": 350, "rating": 4.0, "category": "Stationery", "tags": ["office", "paper", "printing"]},
    {"id": 81, "name": "Wireless Keyboard Slim", "price": 1600, "rating": 4.5, "category": "Electronics", "tags": ["typing", "wireless", "pc"]},
    {"id": 82, "name": "Office Chair Ergonomic", "price": 4200, "rating": 4.7, "category": "Office", "tags": ["chair", "comfort", "work"]},
    {"id": 83, "name": "Table Lamp Adjustable", "price": 1100, "rating": 4.4, "category": "Home", "tags": ["lamp", "study", "lighting"]},
    {"id": 84, "name": "Fountain Pen Premium", "price": 750, "rating": 4.6, "category": "Stationery", "tags": ["pen", "luxury", "writing"]},
    {"id": 85, "name": "Document File Folder", "price": 250, "rating": 4.3, "category": "Office", "tags": ["work", "file", "storage"]},
    {"id": 86, "name": "Wireless Presentation Remote", "price": 1600, "rating": 4.5, "category": "Office", "tags": ["presentation", "wireless", "utility"]},
    {"id": 87, "name": "Desk Mat Large", "price": 799, "rating": 4.4, "category": "Office", "tags": ["desk", "mat", "workspace"]},
    {"id": 88, "name": "Portable Scanner", "price": 3400, "rating": 4.6, "category": "Office", "tags": ["scanner", "work", "digital"]},
    {"id": 89, "name": "USB Flash Drive 64GB", "price": 899, "rating": 4.5, "category": "Electronics", "tags": ["storage", "data", "usb"]},
    {"id": 90, "name": "External Hard Drive 1TB", "price": 4200, "rating": 4.7, "category": "Electronics", "tags": ["storage", "backup", "data"]},
]

# --- Sports & Outdoor (91–110) ---
PRODUCTS += [
    {"id": 91, "name": "Football Size 5", "price": 950, "rating": 4.5, "category": "Sports", "tags": ["outdoor", "ball", "game"]},
    {"id": 92, "name": "Cricket Bat English Willow", "price": 3500, "rating": 4.7, "category": "Sports", "tags": ["cricket", "bat", "outdoor"]},
    {"id": 93, "name": "Badminton Racket Set", "price": 1800, "rating": 4.4, "category": "Sports", "tags": ["indoor", "racket", "fitness"]},
    {"id": 94, "name": "Yoga Block Foam", "price": 550, "rating": 4.3, "category": "Lifestyle", "tags": ["yoga", "exercise", "fitness"]},
    {"id": 95, "name": "Skipping Rope Adjustable", "price": 250, "rating": 4.2, "category": "Sports", "tags": ["workout", "rope", "fitness"]},
    {"id": 96, "name": "Cycling Helmet", "price": 2400, "rating": 4.6, "category": "Outdoor", "tags": ["cycling", "safety", "helmet"]},
    {"id": 97, "name": "Trekking Pole Set", "price": 1700, "rating": 4.5, "category": "Outdoor", "tags": ["trekking", "hiking", "support"]},
    {"id": 98, "name": "Camping Tent 2-Person", "price": 3200, "rating": 4.6, "category": "Outdoor", "tags": ["camping", "outdoor", "travel"]},
    {"id": 99, "name": "Sleeping Bag", "price": 2400, "rating": 4.5, "category": "Outdoor", "tags": ["camping", "sleep", "travel"]},
    {"id": 100, "name": "Hiking Backpack 50L", "price": 3999, "rating": 4.7, "category": "Outdoor", "tags": ["bag", "travel", "hiking"]},
    {"id": 101, "name": "Resistance Band Set", "price": 799, "rating": 4.4, "category": "Sports", "tags": ["workout", "fitness", "stretch"]},
    {"id": 102, "name": "Gym Gloves", "price": 550, "rating": 4.3, "category": "Sports", "tags": ["fitness", "grip", "gym"]},
    {"id": 103, "name": "Basketball Official Size", "price": 950, "rating": 4.6, "category": "Sports", "tags": ["game", "ball", "outdoor"]},
    {"id": 104, "name": "Water Bottle Shaker", "price": 499, "rating": 4.5, "category": "Lifestyle", "tags": ["gym", "bottle", "fitness"]},
    {"id": 105, "name": "Sports Towel Quick Dry", "price": 350, "rating": 4.3, "category": "Lifestyle", "tags": ["towel", "sport", "gym"]},
    {"id": 106, "name": "Camping Lantern Rechargeable", "price": 1200, "rating": 4.5, "category": "Outdoor", "tags": ["lighting", "camping", "portable"]},
    {"id": 107, "name": "Hiking Boots Waterproof", "price": 3800, "rating": 4.8, "category": "Footwear", "tags": ["shoes", "outdoor", "hiking"]},
    {"id": 108, "name": "Compact Binoculars", "price": 2500, "rating": 4.4, "category": "Outdoor", "tags": ["adventure", "view", "travel"]},
    {"id": 109, "name": "Cricket Ball Leather", "price": 350, "rating": 4.2, "category": "Sports", "tags": ["cricket", "ball", "outdoor"]},
    {"id": 110, "name": "Knee Support Sleeve", "price": 600, "rating": 4.3, "category": "Sports", "tags": ["support", "fitness", "recovery"]},


    # --- Fitness & Health (111–130) ---
    {"id": 111, "name": "Adjustable Dumbbell Pair", "price": 2800, "rating": 4.6, "category": "Fitness", "tags": ["weights", "gym", "strength"]},
    {"id": 112, "name": "Foldable Exercise Mat", "price": 1200, "rating": 4.4, "category": "Fitness", "tags": ["yoga", "workout", "comfort"]},
    {"id": 113, "name": "Pull-Up Bar Door Frame", "price": 1900, "rating": 4.5, "category": "Fitness", "tags": ["home", "strength", "workout"]},
    {"id": 114, "name": "Ab Roller Wheel", "price": 850, "rating": 4.3, "category": "Fitness", "tags": ["core", "workout", "home"]},
    {"id": 115, "name": "Treadmill Foldable", "price": 4800, "rating": 4.6, "category": "Fitness", "tags": ["cardio", "home", "exercise"]},
    {"id": 116, "name": "Adjustable Weight Bench", "price": 3500, "rating": 4.7, "category": "Fitness", "tags": ["strength", "bench", "workout"]},
    {"id": 117, "name": "Smart Body Fat Scale", "price": 2200, "rating": 4.5, "category": "Health", "tags": ["smart", "weight", "monitor"]},
    {"id": 118, "name": "Massage Gun Handheld", "price": 3400, "rating": 4.6, "category": "Health", "tags": ["massage", "recovery", "fitness"]},
    {"id": 119, "name": "Protein Shaker Bottle", "price": 499, "rating": 4.4, "category": "Fitness", "tags": ["bottle", "gym", "protein"]},
    {"id": 120, "name": "Smart Blood Pressure Monitor", "price": 2500, "rating": 4.5, "category": "Health", "tags": ["smart", "monitor", "health"]},
    {"id": 121, "name": "Foam Roller Long", "price": 899, "rating": 4.4, "category": "Fitness", "tags": ["recovery", "stretch", "muscle"]},
    {"id": 122, "name": "Skipping Rope Digital Counter", "price": 799, "rating": 4.3, "category": "Fitness", "tags": ["cardio", "rope", "tracking"]},
    {"id": 123, "name": "Ankle Weights 2kg", "price": 999, "rating": 4.2, "category": "Fitness", "tags": ["weights", "leg", "training"]},
    {"id": 124, "name": "Resistance Tube Set", "price": 850, "rating": 4.5, "category": "Fitness", "tags": ["stretch", "bands", "workout"]},
    {"id": 125, "name": "Hand Grip Strengthener", "price": 399, "rating": 4.4, "category": "Fitness", "tags": ["hand", "grip", "training"]},
    {"id": 126, "name": "Heart Rate Monitor Strap", "price": 1600, "rating": 4.5, "category": "Health", "tags": ["heart", "fitness", "tracker"]},
    {"id": 127, "name": "Yoga Wheel", "price": 999, "rating": 4.3, "category": "Fitness", "tags": ["yoga", "stretch", "balance"]},
    {"id": 128, "name": "Push-Up Bar Set", "price": 899, "rating": 4.5, "category": "Fitness", "tags": ["pushup", "home", "strength"]},
    {"id": 129, "name": "Mini Stepper Machine", "price": 3900, "rating": 4.6, "category": "Fitness", "tags": ["cardio", "compact", "workout"]},
    {"id": 130, "name": "Smart Thermometer", "price": 999, "rating": 4.4, "category": "Health", "tags": ["temperature", "smart", "health"]},
]

# --- Beauty & Personal Care (131–150) ---
PRODUCTS += [
    {"id": 131, "name": "Electric Hair Dryer", "price": 1500, "rating": 4.4, "category": "Beauty", "tags": ["hair", "styling", "home"]},
    {"id": 132, "name": "Beard Trimmer", "price": 1300, "rating": 4.5, "category": "Personal Care", "tags": ["grooming", "men", "shaving"]},
    {"id": 133, "name": "Hair Straightener", "price": 1800, "rating": 4.6, "category": "Beauty", "tags": ["hair", "styling", "tools"]},
    {"id": 134, "name": "Face Steamer", "price": 1100, "rating": 4.3, "category": "Beauty", "tags": ["skin", "care", "hydration"]},
    {"id": 135, "name": "Electric Toothbrush", "price": 1900, "rating": 4.5, "category": "Personal Care", "tags": ["dental", "smart", "hygiene"]},
    {"id": 136, "name": "Hair Clippers Kit", "price": 2400, "rating": 4.4, "category": "Personal Care", "tags": ["haircut", "tools", "grooming"]},
    {"id": 137, "name": "Makeup Brush Set (10 pcs)", "price": 999, "rating": 4.5, "category": "Beauty", "tags": ["makeup", "brushes", "cosmetics"]},
    {"id": 138, "name": "Compact Mirror LED", "price": 650, "rating": 4.3, "category": "Beauty", "tags": ["mirror", "portable", "light"]},
    {"id": 139, "name": "Men’s Shaving Kit", "price": 1500, "rating": 4.2, "category": "Personal Care", "tags": ["shaving", "kit", "men"]},
    {"id": 140, "name": "Facial Cleanser Brush", "price": 1300, "rating": 4.4, "category": "Beauty", "tags": ["face", "cleansing", "skincare"]},
    {"id": 141, "name": "Nail Grooming Set", "price": 799, "rating": 4.5, "category": "Personal Care", "tags": ["nails", "grooming", "kit"]},
    {"id": 142, "name": "Perfume Set (Unisex)", "price": 2100, "rating": 4.6, "category": "Beauty", "tags": ["fragrance", "luxury", "gift"]},
    {"id": 143, "name": "Hair Serum 100ml", "price": 499, "rating": 4.3, "category": "Beauty", "tags": ["hair", "care", "shine"]},
    {"id": 144, "name": "Moisturizing Cream", "price": 550, "rating": 4.4, "category": "Beauty", "tags": ["skin", "hydration", "care"]},
    {"id": 145, "name": "Lip Balm Set", "price": 350, "rating": 4.2, "category": "Beauty", "tags": ["lip", "care", "hydration"]},
    {"id": 146, "name": "Hair Comb Anti-Static", "price": 199, "rating": 4.1, "category": "Beauty", "tags": ["hair", "tool", "grooming"]},
    {"id": 147, "name": "Beard Oil 30ml", "price": 499, "rating": 4.4, "category": "Personal Care", "tags": ["beard", "oil", "care"]},
    {"id": 148, "name": "Compact Makeup Organizer", "price": 899, "rating": 4.5, "category": "Beauty", "tags": ["storage", "makeup", "vanity"]},
    {"id": 149, "name": "Electric Shaver 3D", "price": 2500, "rating": 4.6, "category": "Personal Care", "tags": ["shaving", "electric", "men"]},
    {"id": 150, "name": "Hair Dryer Brush Combo", "price": 2200, "rating": 4.5, "category": "Beauty", "tags": ["hair", "styling", "combo"]},
]
